CUDA_VISIBLE_DEVICES=2 python dps_promptir_infer.py \
  --data_root /home/joon/ImageRestoration-AllInOne/Combined_Method/aoiir/datasets/dataset \
  --sd_model stabilityai/stable-diffusion-2-1-base \
  --adapter_ckpt /home/joon/ImageRestoration-AllInOne/Combined_Method/runs/dps_promptir/lightning_logs/version_16/checkpoints/epoch=3-step=44785.ckpt \
  --subset_ratio 0.0005 \
  --batch_size 16 \
  --steps 1000 \
  --stoc_avg_steps 3 \
  --rand_num 3 \
  --sampling_method combined_dps \
  --pixel_dps_scale 1 \
  --second_order_scale 0.03 \
  --dps_scale 1 \
  --cfg 10 \
  --do_classifier_free_guidance False \
  --scheduler_type ddim \
  --manifold_eq False \
  --num_forwards 3 \
  --out_dir /home/joon/ImageRestoration-AllInOne/Combined_Method/inference_combined_dps_promptir_3forwards